# Bootcamp Introducción a Python II

Manuel Montoya | Data Scientist

# numpy

Documentation: https://numpy.org

In [1]:
import numpy

In [2]:
numpy.__version__

'1.21.0'

In [3]:
import numpy as np

In [4]:
np.__version__

'1.21.0'

np.array

vectorized functions: sum, product, division

atributes, methods, functions

methods

functions

Función sigmoidal para cada elemento?
\begin{equation*}
\frac{1}{(1+e^{-x})}
\end{equation*}

Comparación de tiempos de ejecución

<img src='https://miro.medium.com/max/640/1*htL9RL4Z9EG2YbrSyuYNrw.webp'>

Generación de arreglos de numpy: np.ones, np.random.normal

histogram

slicing, indexing, masks

mask

dimensions

# Exercises

Create a function that calculates how many numbers are even in a given array

Implement the relu function (function recieves and array and applies ReLU)

<img src='https://miro.medium.com/max/357/1*oePAhrm74RNnNEolprmTaQ.png'>

Create a function that recieves a number n and creates a matrix of shape nxn of numbers smaller than n squared

Write a function that creates a chess table (*hint*: try using a numpy function)

```
array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])
```

Write a function that standarizes the results of a numpy array (substracts mean and divides by standard deviation)

Write a function that zero pads an array

```
input

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])
```

```
output
array([[0., 0., 0., 0.],
       [0., 1., 2., 0.],
       [0., 3., 4., 0.],
       [0., 5., 6., 0.],
       [0., 7., 8., 0.],
       [0., 0., 0., 0.]])
```

Write a function that reverses the order of the rows in a matrix

```
input
array([[61, 82, 89, 98],
       [34, 43, 13, 75],
       [23, 12, 94, 68],
       [36, 39, 72, 51],
       [57, 39, 92, 20]])
       
output
array([[57, 39, 92, 20],
       [36, 39, 72, 51],
       [23, 12, 94, 68],
       [34, 43, 13, 75],
       [61, 82, 89, 98]])

```

Write a function that reverses the order of the columns in a matrix

```
input
array([[61, 82, 89, 98],
       [34, 43, 13, 75],
       [23, 12, 94, 68],
       [36, 39, 72, 51],
       [57, 39, 92, 20]])
       
output
array([[98, 89, 82, 61],
       [75, 13, 43, 34],
       [68, 94, 12, 23],
       [51, 72, 39, 36],
       [20, 92, 39, 57]])

```

Write a function that reverses the order of the items in a matrix

```
input
array([[61, 82, 89, 98],
       [34, 43, 13, 75],
       [23, 12, 94, 68],
       [36, 39, 72, 51],
       [57, 39, 92, 20]])
       
output
array([[20, 92, 39, 57],
       [51, 72, 39, 36],
       [68, 94, 12, 23],
       [75, 13, 43, 34],
       [98, 89, 82, 61]])

```

Create a function that multiplies two matrices. If the product is not possible the function should print an error message