# Bootcamp Introducción a Python II

Manuel Montoya | Data Scientist

# numpy

Documentation: https://numpy.org

In [1]:
import numpy

In [2]:
numpy.__version__

'1.26.1'

In [3]:
import numpy as np

In [4]:
np.__version__

'1.26.1'

np.array

In [6]:
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [8]:
np_array = np.array(lista)
np_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
type(np_array)

numpy.ndarray

In [12]:
np_array[::2]

array([1, 3, 5, 7, 9])

In [13]:
np_array.sum()

55

In [14]:
np_array.size

10

vectorized functions: sum, product, division

In [15]:
lista_1 = list(range(1,11))
lista_2 = list(range(11,21))

In [16]:
lista_1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [17]:
lista_2

[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [18]:
lista_1 + lista_2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [20]:
lista_1 * 2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [21]:
array_1 = np.array(lista_1)
array_2 = np.array(lista_2)

In [22]:
array_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
array_2

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [24]:
array_1 + array_2

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [25]:
array_1 * 3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [26]:
array_1 * array_2

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171, 200])

In [27]:
lista_1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [28]:
[x**2 for x in lista_1]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [29]:
array_1 ** 2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [30]:
array_1 / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

metodos y funciones

In [31]:
array_1.std()

2.8722813232690143

In [32]:
np.std(array_1)

2.8722813232690143

Función sigmoidal para cada elemento?
\begin{equation*}
\frac{1}{(1+e^{-x})}
\end{equation*}

In [37]:
x = 5

1 / (1 + np.exp(-x))

0.9933071490757153

In [33]:
array_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
1 / (1 + np.exp(-array_1))

array([0.73105858, 0.88079708, 0.95257413, 0.98201379, 0.99330715,
       0.99752738, 0.99908895, 0.99966465, 0.99987661, 0.9999546 ])

Comparación de tiempos de ejecución

In [39]:
lista_numeros = range(1_000_000)

In [40]:
%timeit sum(lista_numeros)

10.8 ms ± 481 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [41]:
np_array = np.array(lista_numeros)

In [42]:
%timeit np_array.sum()

135 μs ± 6.97 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


<img src='https://miro.medium.com/max/640/1*htL9RL4Z9EG2YbrSyuYNrw.webp'>

Generación de arreglos de numpy: np.ones, np.random.normal

histogram

slicing, indexing, masks

mask

dimensions

# Exercises

Create a function that calculates how many numbers are even in a given array

Implement the relu function (function recieves and array and applies ReLU)

<img src='https://miro.medium.com/max/357/1*oePAhrm74RNnNEolprmTaQ.png'>

Create a function that recieves a number n and creates a matrix of shape nxn of numbers smaller than n squared

Write a function that creates a chess table (*hint*: try using a numpy function)

```
array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])
```

Write a function that standarizes the results of a numpy array (substracts mean and divides by standard deviation)

Write a function that zero pads an array

```
input

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])
```

```
output
array([[0., 0., 0., 0.],
       [0., 1., 2., 0.],
       [0., 3., 4., 0.],
       [0., 5., 6., 0.],
       [0., 7., 8., 0.],
       [0., 0., 0., 0.]])
```

Write a function that reverses the order of the rows in a matrix

```
input
array([[61, 82, 89, 98],
       [34, 43, 13, 75],
       [23, 12, 94, 68],
       [36, 39, 72, 51],
       [57, 39, 92, 20]])
       
output
array([[57, 39, 92, 20],
       [36, 39, 72, 51],
       [23, 12, 94, 68],
       [34, 43, 13, 75],
       [61, 82, 89, 98]])

```

Write a function that reverses the order of the columns in a matrix

```
input
array([[61, 82, 89, 98],
       [34, 43, 13, 75],
       [23, 12, 94, 68],
       [36, 39, 72, 51],
       [57, 39, 92, 20]])
       
output
array([[98, 89, 82, 61],
       [75, 13, 43, 34],
       [68, 94, 12, 23],
       [51, 72, 39, 36],
       [20, 92, 39, 57]])

```

Write a function that reverses the order of the items in a matrix

```
input
array([[61, 82, 89, 98],
       [34, 43, 13, 75],
       [23, 12, 94, 68],
       [36, 39, 72, 51],
       [57, 39, 92, 20]])
       
output
array([[20, 92, 39, 57],
       [51, 72, 39, 36],
       [68, 94, 12, 23],
       [75, 13, 43, 34],
       [98, 89, 82, 61]])

```

Create a function that multiplies two matrices. If the product is not possible the function should print an error message